knpu_oauth2_client:
    clients:
        adobe_sign:
            type: generic
            provider_class: Postyou\AdobeSignBundle\Client\AdobeSignProvider
            client_class: Postyou\AdobeSignBundle\Client\AdobeSignClient
            client_id: '%env(ADOBE_SIGN_CLIENT_ID)%'
            client_secret: '%env(ADOBE_SIGN_CLIENT_SECRET)%'
            redirect_route: adobe_auth_check
            redirect_params: {}
            provider_options:
                web_access_point: 'https://secure.eu2.adobesign.com/'
                api_access_point: 'https://api.eu2.adobesign.com'
                path_oauth: 'public/oauth'
                path_refresh: 'oauth/refresh'
                path_token: 'oauth/token'
                path_revoke: 'oauth/revoke'
