services:
    _defaults:
        autowire: true

    Postyou\AdobeSignBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources}

    Postyou\AdobeSignBundle\Provider\AccessTokenManager:
        arguments:
            $projectDir: '%kernel.project_dir%'
