services:
    _defaults:
        autowire: true

    Postyou\AdobeSignBundle\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources}

    Postyou\AdobeSignBundle\Client\AccessTokenManager:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Postyou\AdobeSignBundle\Client\AdobeSignProvider:
        properties:
            api_access_point: '%env(ADOBE_SIGN_API_ACCESS_POINT)%'
            web_access_point: '%env(ADOBE_SIGN_WEB_ACCESS_POINT)%'
